<?php

	namespace App\Model\Table;

	use Cake\Event\EventInterface;
    use Cake\ORM\Table;
    use Cake\Utility\Text;

    class ArticlesTable extends Table
	{
        public function beforeSave(EventInterface $event, $entity, $options)
        {
            if ($entity->isNew() && !$entity->slug) {
                $sluggedTitle = Text::slug(strtolower($entity->title));
                // trim slug to maximum length defined in schema
                $entity->slug = substr($sluggedTitle, 0, 191);
            }
        }

        public function initialize (array $config): void
        {
            parent::initialize($config); // TODO: Change the autogenerated stub
            $this->addBehavior('Timestamp');
        }
    }
