<?php

	namespace App\Model\Table;

	use Cake\Event\EventInterface;
    use Cake\ORM\Table;
    use Cake\Utility\Text;
    use Cake\Validation\Validator;

    class ArticlesTable extends Table
	{
        public function beforeSave(EventInterface $event, $entity, $options)
        {
            if ($entity->isNew() && !$entity->slug) {
                $sluggedTitle = Text::slug(strtolower($entity->title));
                // trim slug to maximum length defined in schema
                $entity->slug = substr($sluggedTitle, 0, 191);
            }
        }

        public function initialize (array $config): void
        {
            parent::initialize($config); // TODO: Change the autogenerated stub
            $this->addBehavior('Timestamp');
            $this->belongsToMany('Tags');
        }

        public function validationDefault (Validator $validator): Validator
        {
            $validator->notEmptyString('title')
                ->minLength('title', 10)
                ->maxLength('title', 255)
                ->notEmptyString('body')
                ->minLength('body', 10);
            return $validator;
        }
    }
